describe('happy path', () => {
  it('input and get to next page', () => {
    cy.visit('http://localhost:5173')
    cy.contains('Personal info')
    cy.get('input[type= "text"]').type('Hello man')
    cy.get('input[type= "email"]').type('helloman@hello.world')
    cy.get('input[type= "tel"]').type('+123123123')
    cy.get('button.next').click()
    cy.contains('Select your plan')
    cy.get('.card').eq(0).click()
    cy.get('label .container__switch').click()
    cy.get('button.next').click()
    cy.get('.card__checkbox').eq(0).click()
    cy.get('.card__checkbox').eq(2).click()
    cy.get('button.next').click()
    cy.contains('Finishing up')
    cy.get('.tier__name').contains('Arcade (Yearly)')
    cy.get('.tier__price').contains('$90/yr')
    cy.get('.container__price .name').eq(0).contains('Online service')
    cy.get('.container__price .price').eq(0).contains('+$10/yr')
    cy.get('.container__price .name').eq(1).contains('Customizable profile')
    cy.get('.container__price .price').eq(1).contains('$20/yr')
    cy.get('.total__price').contains('$120/yr')
    cy.get('button.next').click()
    cy.contains('Thank you')
  })
})
